export const isA = Array.isArray;
export const fr = Array.from;
export const of = Array.of;
export const mp = (a, f) => a.map(f);
export const fl = (a, f) => a.filter(f);
export const rd = (a, f, i) => a.reduce(f, i);
export const fe = (a, f) => a.forEach(f);
export const fn = (a, f) => a.find(f);
export const fi = (a, f) => a.findIndex(f);
export const sm = (a, f) => a.some(f);
export const ev = (a, f) => a.every(f);
export const inc = (a, v) => a.includes(v);
export const sl = (a, b, e) => a.slice(b, e);
export const sp = (a, b, e) => a.splice(b, e);
export const jn = (a, s) => a.join(s);
export const cn = (a, ...v) => a.concat(...v);
export const rv = a => a.reverse();
export const st = (a, f) => a.sort(f);
export const flt = (a, d) => a.flat(d);
export const fm = (a, f) => a.flatMap(f);

export const ia = (a, v) => a?.indexOf(v);
export const us = (a) => [...new Set(a)];
export const ic = (a, v) => a?.includes(v);
