export const ok = Object.keys;
export const ov = Object.values;
export const oe = Object.entries;
export const oa = Object.assign;
export const oc = Object.create;
export const od = Object.defineProperty;
export const op = Object.getOwnPropertyDescriptor;
export const oz = Object.freeze;
export const os = Object.seal;
export const fr = Object.fromEntries;
export const gp = Object.getPrototypeOf;
export const sp = Object.setPrototypeOf;
export const jp = JSON.parse;
export const js = JSON.stringify;
export const nw = Date.now;
export const tf = v => typeof v;
export const io = (i, c) => i instanceof c;
export const nn = v => v != null;
export const isS = v => typeof v === 'string';
export const isN = v => typeof v === 'number';
export const isO = v => typeof v === 'object' && v !== null;
export const isF = v => typeof v === 'function';
export const isB = v => typeof v === 'boolean';
export const isU = v => v === undefined;
export const isNl = v => v === null;
export const E = Error;
export const TE = TypeError;
export const RE = ReferenceError;
export const SE = SyntaxError;
export const RGE = RangeError;
