export const js = (o) => JSON.stringify(o);
export const jp = (s) => JSON.parse(s);
export const jf = (o) => JSON.stringify(o, null, 2);
export const jstr = jf;
export const jpar = jp;
export const ks = (o) => Object.keys(o);
export const vs = (o) => Object.values(o);
export const es = (o) => Object.entries(o);
export const as = (t, ...s) => Object.assign(t, ...s);
export const oa = as;
export const hk = (o, k) => Object.hasOwnProperty.call(o, k);
export const hp = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
export const fr = (o, e) => Object.fromEntries(e);
export const isA = (v) => Array.isArray(v);
export const isO = (v) => typeof v === "object" && v !== null;
export const isS = (v) => typeof v === "string";
export const isN = (v) => typeof v === "number";
export const isB = (v) => typeof v === "boolean";
export const isF = (v) => typeof v === "function";
export const isU = (v) => typeof v === "undefined";
export const isNl = (v) => v === null;
export const isNn = (v) => v != null;
export const isNaN2 = (v) => Number.isNaN(v);
export const isFin = (v) => Number.isFinite(v);
export const isInt = (v) => Number.isInteger(v);
export const pI = (s) => parseInt(s, 10);
export const pF = (s) => parseFloat(s);
export const nv = (v) => Number(v);
export const bv = (v) => Boolean(v);
export const sv = (v) => String(v);
export const enc = (s) => encodeURIComponent(s);
export const dec = (s) => decodeURIComponent(s);
export const b64e = (s) => btoa(s);
export const b64d = (s) => atob(s);
