export const qs = (s, r = document) => r.querySelector(s);
export const qsa = (s, r = document) => r.querySelectorAll(s);
export const qa = (s, r = document) => [...r.querySelectorAll(s)];
export const ce = (t) => document.createElement(t);
export const gebi = (i) => document.getElementById(i);
export const ap = (p, c) => p.appendChild(c);
export const tc = (e, t) => (t === undefined ? e.textContent : (e.textContent = t));
export const ih = (e, h) => (h === undefined ? e.innerHTML : (e.innerHTML = h));
export const vl = (e, v) => (v === undefined ? e.value : (e.value = v));
export const rc = (e, c) => e.classList.remove(c);
export const ac = (e, c) => e.classList.add(c);
export const tx = (t) => document.createTextNode(t);
export const fc = (n, f) => n.forEach(f);
