export const d = document;
export const dc = document;
export const win = window;
export const loc = location;
export const qs = (s, r = document) => r.querySelector(s);
export const $ = qs;
export const qsa = (s, r = document) => r.querySelectorAll(s);
export const $$ = qsa;
export const qa = (s, r = document) => [...r.querySelectorAll(s)];
export const ge = i => document.getElementById(i);
export const id = ge;
export const gebi = ge;
export const ce = t => document.createElement(t);
export const tx = t => document.createTextNode(t);
export const ap = (p, c) => p.appendChild(c);
export const rm = e => e?.remove();
export const tc = (e, t) => (t === undefined ? e.textContent : (e.textContent = t));
export const ih = (e, h) => (h === undefined ? e.innerHTML : (e.innerHTML = h));
export const vl = (e, v) => (v === undefined ? e.value : (e.value = v));
export const rc = (e, c) => e.classList.remove(c);
export const ac = (e, c) => e.classList.add(c);
export const tc2 = (e, c) => e.classList.toggle(c);
export const hc = (e, c) => e.classList.contains(c);
export const ael = (e, t, f, o) => e.addEventListener(t, f, o);
export const on = ael;
export const rel = (e, t, f, o) => e.removeEventListener(t, f, o);
export const of = rel;
export const off = rel;
export const fc = e => e.firstChild;
export const vs = (e, v) => (e.style.display = v ? '' : 'none');
export const forEach = (n, f) => n.forEach(f);
