export const d = document;
export const dt = (t) => (t === undefined ? d.title : (d.title = t));
export const qs = (s, p = d) => p.querySelector(s);
export const $ = qs;
export const qsa = (s, p = d) => [...p.querySelectorAll(s)];
export const $$ = qsa;
export const ce = (t) => d.createElement(t);
export const ae = (e, t, h) => e.addEventListener(t, h);
export const re = (e, t, h) => e.removeEventListener(t, h);
export const ap = (p, c) => p.appendChild(c);
export const on = ae;
export const id = (i) => d.getElementById(i);
export const ge = id;
export const vs = (e, v) => (e.style.display = v ? '' : 'none');
export const off = (e, t, h) => e.removeEventListener(t, h);
export const txt = (e, t) => (e.textContent = t);
export const html = (e, h) => (e.innerHTML = h);
