export const c = console;
export const log = (...a) => c.log(...a);
export const err = (...a) => c.error(...a);
export const warn = (...a) => c.warn(...a);
export const rt = chrome.runtime;
export const st = setTimeout;
export const m = Math;
export const mf = n => m.floor(n);
export const sb = (s, a, b) => s.substring(a, b);
export const rp = (s, a, b) => s.replace(a, b);
export const mp = (a, f) => a.map(f);
export const jn = (a, s) => a.join(s);
export const cw = chrome.windows;
export const sg = (...a) => chrome.storage.local.get(...a);
export const slc = (...a) => chrome.storage.local.clear(...a);
export const msg = (...a) => rt.sendMessage(...a);
export const jp = JSON.parse;
export const js = JSON.stringify;
export const oe = Object.entries;
export const pI = (...a) => rt.getPlatformInfo(...a);
export const si = setInterval;
export const csi = clearInterval;
export const loc = location;
export const ct = clearTimeout;
export const oa = Object.assign;
export const Er = Error;
